using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProductionPlanner.Data;

#nullable disable

namespace ProductionPlanner.Migrations
{
    /// <summary>
    /// Chat tables. Idempotent SQL so apply-migrations is safe if startup patches already created them.
    /// </summary>
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710120000_AddChatTables")]
    public partial class AddChatTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "ChatConversations" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Type" integer NOT NULL,
                    "UserIdLow" character varying(450) NULL,
                    "UserIdHigh" character varying(450) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_ChatConversations_Type"
                    ON "ChatConversations" ("Type");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_ChatConversations_UserIdLow_UserIdHigh"
                    ON "ChatConversations" ("UserIdLow", "UserIdHigh");

                CREATE TABLE IF NOT EXISTS "ChatMessages" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ConversationId" bigint NOT NULL,
                    "SenderUserId" character varying(450) NOT NULL,
                    "Text" character varying(4000) NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "FK_ChatMessages_ChatConversations_ConversationId"
                        FOREIGN KEY ("ConversationId") REFERENCES "ChatConversations" ("Id") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS "IX_ChatMessages_ConversationId_Id"
                    ON "ChatMessages" ("ConversationId", "Id");

                CREATE TABLE IF NOT EXISTS "ChatReadStates" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" character varying(450) NOT NULL,
                    "ConversationId" bigint NOT NULL,
                    "LastReadMessageId" bigint NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "FK_ChatReadStates_ChatConversations_ConversationId"
                        FOREIGN KEY ("ConversationId") REFERENCES "ChatConversations" ("Id") ON DELETE CASCADE
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_ChatReadStates_UserId_ConversationId"
                    ON "ChatReadStates" ("UserId", "ConversationId");

                CREATE TABLE IF NOT EXISTS "ChatAttachments" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "MessageId" bigint NOT NULL,
                    "FileName" character varying(260) NOT NULL,
                    "ContentType" character varying(120) NOT NULL,
                    "SizeBytes" bigint NOT NULL,
                    "StoragePath" character varying(500) NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "FK_ChatAttachments_ChatMessages_MessageId"
                        FOREIGN KEY ("MessageId") REFERENCES "ChatMessages" ("Id") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS "IX_ChatAttachments_MessageId"
                    ON "ChatAttachments" ("MessageId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "ChatAttachments";
                DROP TABLE IF EXISTS "ChatMessages";
                DROP TABLE IF EXISTS "ChatReadStates";
                DROP TABLE IF EXISTS "ChatConversations";
                """);
        }
    }
}
