using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProductionPlanner.Data;

#nullable disable

namespace ProductionPlanner.Migrations
{
    /// <summary>
    /// Web Push subscriptions. Idempotent SQL so apply-migrations is safe if startup patches already created the table.
    /// </summary>
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710141500_AddWebPushSubscriptions")]
    public partial class AddWebPushSubscriptions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "WebPushSubscriptions" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" character varying(450) NOT NULL,
                    "Endpoint" character varying(2048) NOT NULL,
                    "P256dh" character varying(256) NOT NULL,
                    "Auth" character varying(128) NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_WebPushSubscriptions_Endpoint"
                    ON "WebPushSubscriptions" ("Endpoint");
                CREATE INDEX IF NOT EXISTS "IX_WebPushSubscriptions_UserId"
                    ON "WebPushSubscriptions" ("UserId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "WebPushSubscriptions";
                """);
        }
    }
}
