using Microsoft.EntityFrameworkCore;
using ProductionPlanner.Data;

namespace ProductionPlanner.Infrastructure;

/// <summary>
/// Применение EF-миграций и совместимости схемы PostgreSQL (деплой / CLI, не при каждом старте IIS).
/// </summary>
public static class PostgresSchemaMigrator
{
    public static async Task ApplyAsync(
        ApplicationDbContext db,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (!db.Database.IsNpgsql())
            throw new InvalidOperationException("PostgresSchemaMigrator вызывается только для PostgreSQL.");

        await db.Database.MigrateAsync(cancellationToken);
        logger.LogInformation("Схема PostgreSQL применена (EF migrations).");

        await PostgresLegacySchemaRepair.RepairAsync(db, logger);
        await ApplyUserNotificationsPatchAsync(db, logger, cancellationToken);
    }

    private static async Task ApplyUserNotificationsPatchAsync(
        ApplicationDbContext db,
        ILogger logger,
        CancellationToken cancellationToken)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "UserNotifications" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" text NOT NULL,
                    "Type" character varying(50) NOT NULL,
                    "TaskId" integer,
                    "Title" character varying(500) NOT NULL,
                    "Deadline" timestamp with time zone,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "AcknowledgedAt" timestamp with time zone
                );
                CREATE INDEX IF NOT EXISTS "IX_UserNotifications_UserId_AcknowledgedAt"
                    ON "UserNotifications" ("UserId", "AcknowledgedAt");
                """, cancellationToken);
            logger.LogInformation("Таблица UserNotifications проверена/создана (PostgreSQL).");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Ошибка при обновлении схемы PostgreSQL (UserNotifications)");
            throw;
        }
    }
}
