using Microsoft.EntityFrameworkCore;
using ProductionPlanner.Data;

namespace ProductionPlanner.Infrastructure;

/// <summary>
/// Применение EF-миграций и совместимости схемы PostgreSQL (деплой / CLI, не при каждом старте IIS).
/// </summary>
public static class PostgresSchemaMigrator
{
    public static async Task ApplyAsync(
        ApplicationDbContext db,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (!db.Database.IsNpgsql())
            throw new InvalidOperationException("PostgresSchemaMigrator вызывается только для PostgreSQL.");

        await db.Database.MigrateAsync(cancellationToken);
        logger.LogInformation("Схема PostgreSQL применена (EF migrations).");

        await ApplyCompatibilityPatchesAsync(db, logger, cancellationToken);
    }

    /// <summary>
    /// Идемпотентные ALTER/CREATE для колонок вне цепочки EF или если apply-migrations не запускался при деплое.
    /// </summary>
    public static async Task ApplyCompatibilityPatchesAsync(
        ApplicationDbContext db,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (!db.Database.IsNpgsql())
            return;

        await ApplyProductionTasksCompatibilityPatchAsync(db, logger, cancellationToken);
        await ApplyUserNotificationsPatchAsync(db, logger, cancellationToken);
        await ApplyLunchIntervalsPatchAsync(db, logger, cancellationToken);
        await ApplyTaskCdrPreviewsPatchAsync(db, logger, cancellationToken);
        await ApplyPhase2PerformanceIndexesPatchAsync(db, logger, cancellationToken);
    }

    private static async Task ApplyProductionTasksCompatibilityPatchAsync(
        ApplicationDbContext db,
        ILogger logger,
        CancellationToken cancellationToken)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                ALTER TABLE "ProductionTasks"
                    ADD COLUMN IF NOT EXISTS "SupplyMode" integer NOT NULL DEFAULT 0;

                ALTER TABLE "ProductionTasks"
                    ADD COLUMN IF NOT EXISTS "HiddenFromTaskTable" boolean NOT NULL DEFAULT false;

                ALTER TABLE "ProductionTasks"
                    ADD COLUMN IF NOT EXISTS "RequiresTestBeforeProduction" boolean NOT NULL DEFAULT false;

                ALTER TABLE "ProductionTasks"
                    ADD COLUMN IF NOT EXISTS "TestEstimateHours" double precision NOT NULL DEFAULT 0;

                ALTER TABLE "ProductionTasks"
                    ADD COLUMN IF NOT EXISTS "ProductionEstimateHours" double precision NOT NULL DEFAULT 0;

                ALTER TABLE "ProductionTasks"
                    ADD COLUMN IF NOT EXISTS "WorkPhase" integer NOT NULL DEFAULT 0;

                ALTER TABLE "ProductionTasks"
                    ADD COLUMN IF NOT EXISTS "TestPhaseCompletedAt" timestamp with time zone NULL;

                ALTER TABLE "TaskSplits"
                    ADD COLUMN IF NOT EXISTS "SequenceOrder" integer NOT NULL DEFAULT 0;

                ALTER TABLE "TaskSplits"
                    ADD COLUMN IF NOT EXISTS "IsApprovalTestPart" boolean NOT NULL DEFAULT false;

                ALTER TABLE "TaskSplits"
                    ADD COLUMN IF NOT EXISTS "ApprovalGateTestChildId" integer NULL;
                """, cancellationToken);
            logger.LogInformation("Колонки совместимости ProductionTasks/TaskSplits проверены/созданы (PostgreSQL).");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Ошибка при обновлении схемы PostgreSQL (ProductionTasks/TaskSplits)");
            throw;
        }
    }

    private static async Task ApplyUserNotificationsPatchAsync(
        ApplicationDbContext db,
        ILogger logger,
        CancellationToken cancellationToken)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "UserNotifications" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" text NOT NULL,
                    "Type" character varying(50) NOT NULL,
                    "TaskId" integer,
                    "Title" character varying(500) NOT NULL,
                    "Deadline" timestamp with time zone,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "AcknowledgedAt" timestamp with time zone
                );
                CREATE INDEX IF NOT EXISTS "IX_UserNotifications_UserId_AcknowledgedAt"
                    ON "UserNotifications" ("UserId", "AcknowledgedAt");
                """, cancellationToken);
            logger.LogInformation("Таблица UserNotifications проверена/создана (PostgreSQL).");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Ошибка при обновлении схемы PostgreSQL (UserNotifications)");
            throw;
        }
    }

    private static async Task ApplyLunchIntervalsPatchAsync(
        ApplicationDbContext db,
        ILogger logger,
        CancellationToken cancellationToken)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "LunchIntervals" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "EmployeeName" character varying(100) NOT NULL,
                    "StartTime" timestamp with time zone NOT NULL,
                    "EndTime" timestamp with time zone
                );
                CREATE INDEX IF NOT EXISTS "IX_LunchIntervals_EmployeeName_StartTime"
                    ON "LunchIntervals" ("EmployeeName", "StartTime");
                CREATE INDEX IF NOT EXISTS "IX_LunchIntervals_EmployeeName_EndTime"
                    ON "LunchIntervals" ("EmployeeName", "EndTime");
                """, cancellationToken);
            logger.LogInformation("Таблица LunchIntervals проверена/создана (PostgreSQL).");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Ошибка при обновлении схемы PostgreSQL (LunchIntervals)");
            throw;
        }
    }

    private static async Task ApplyTaskCdrPreviewsPatchAsync(
        ApplicationDbContext db,
        ILogger logger,
        CancellationToken cancellationToken)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "TaskCdrPreviews" (
                    "TaskId" integer NOT NULL PRIMARY KEY,
                    "ContentType" character varying(64) NOT NULL DEFAULT 'image/webp',
                    "Data" bytea NOT NULL DEFAULT '\x'::bytea,
                    "ByteSize" integer NOT NULL DEFAULT 0,
                    "SourceKey" character varying(512) NOT NULL DEFAULT '',
                    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT "FK_TaskCdrPreviews_ProductionTasks_TaskId"
                        FOREIGN KEY ("TaskId") REFERENCES "ProductionTasks" ("Id") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS "IX_TaskCdrPreviews_UpdatedAt"
                    ON "TaskCdrPreviews" ("UpdatedAt");
                """, cancellationToken);
            logger.LogInformation("Таблица TaskCdrPreviews проверена/создана (PostgreSQL).");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Ошибка при обновлении схемы PostgreSQL (TaskCdrPreviews)");
            throw;
        }
    }

    private static async Task ApplyPhase2PerformanceIndexesPatchAsync(
        ApplicationDbContext db,
        ILogger logger,
        CancellationToken cancellationToken)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE INDEX IF NOT EXISTS "IX_WorkIntervals_OpenInterval"
                    ON "WorkIntervals" ("ProductionTaskId")
                    WHERE "EndTime" IS NULL;

                CREATE INDEX IF NOT EXISTS "IX_WorkIntervals_RangeLookup"
                    ON "WorkIntervals" ("StartTime", "EndTime");

                CREATE INDEX IF NOT EXISTS "IX_ProductionTasks_EmployeeName_CompletedAt"
                    ON "ProductionTasks" ("EmployeeName", "CompletedAt")
                    WHERE "Status" = 3;

                CREATE INDEX IF NOT EXISTS "IX_ProductionTasks_RootTableVisible"
                    ON "ProductionTasks" ("DisplayOrder" DESC, "Id" DESC)
                    WHERE "ParentRowNumber" IS NULL AND NOT "HiddenFromTaskTable";

                CREATE INDEX IF NOT EXISTS "IX_Users_FullName"
                    ON "Users" ("FullName");
                """, cancellationToken);
            logger.LogInformation("Индексы производительности (phase 2) проверены/созданы (PostgreSQL).");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Ошибка при создании индексов производительности (PostgreSQL)");
            throw;
        }
    }
}
